//------------------------------------------------------------------------------
//
//  Copyright (c) 2016 Glympse Inc. All rights reserved.
//
//------------------------------------------------------------------------------

@interface GlyEnRouteEvents : NSObject
{
}

+ (int)LISTENER_ENROUTE_MANAGER;

+ (int)LISTENER_TASKS;

+ (int)LISTENER_AGENTS;

+ (int)LISTENER_SESSIONS;

+ (int)LISTENER_ACTIVE_AGENTS;

+ (int)LISTENER_ETA_PLANNER;

+ (int)ENROUTE_MANAGER_LOGIN_COMPLETED;

+ (int)ENROUTE_MANAGER_LOGGED_OUT;

+ (int)ENROUTE_MANAGER_STARTED;

+ (int)ENROUTE_MANAGER_STOPPED;

+ (int)ENROUTE_MANAGER_SYNCED;

+ (int)ENROUTE_MANAGER_SHOW_NOTIFICATION;

+ (int)ENROUTE_MANAGER_AUTHENTICATION_NEEDED;

+ (int)ENROUTE_MANAGER_ORG_CONFIG_UPDATED;

+ (int)ENROUTE_MANAGER_SELF_AGENT_UPDATED;

+ (int)TASKS_TASK_LIST_CHANGED;

+ (int)TASKS_TASK_STARTED;

+ (int)TASKS_TASK_START_FAILED;

+ (int)TASKS_OPERATION_COMPLETED;

+ (int)TASKS_OPERATION_COMPLETION_FAILED;

+ (int)TASKS_TASK_PHASE_CHANGED;

+ (int)TASKS_OPERATION_TICKET_CHANGED;

+ (int)ETA_PLANNER_ETAS_UPDATED;

+ (int)AGENTS_AGENT_LIST_CHANGED;

+ (int)AGENTS_AGENT_CREATED;

+ (int)AGENTS_AGENT_CREATION_FAILED;

+ (int)AGENTS_AGENT_UPDATED;

+ (int)AGENTS_AGENT_UPDATE_FAILED;

+ (int)SESSIONS_SESSION_LIST_CHANGED;

+ (int)SESSIONS_SESSION_STARTED;

+ (int)SESSIONS_SESSION_START_FAILED;

+ (int)SESSIONS_SESSION_COMPLETED;

+ (int)SESSIONS_SESSION_COMPLETION_FAILED;

+ (int)SESSIONS_SESSION_ACTIVE_TASK_CHANGED;

+ (int)SESSIONS_SESSION_ACTIVE_TASK_PHASE_CHANGED;

+ (int)ACTIVE_AGENTS_AGENT_LIST_CHANGED;

+ (int)ACTIVE_AGENTS_AGENT_REGISTERED;

@end